argo-cd:
  redis:
    enabled: true
    metrics:
      enabled: true

  controller:
    metrics:
      enabled: true
      applicationLabels:
        enabled: true
        labels: ["name", "instance"]

  repoServer:
    metrics:
      enabled: true

  notifications:
    metrics:
      enabled: true

  server:
    metrics:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - "tucson-teststand.lsst.codes"
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      paths:
        - /argo-cd(/|$)(.*)

    extraArgs:
      - "--basehref=/argo-cd"
      - "--insecure=true"

    config:
      url: https://tucson-teststand.lsst.codes/argo-cd
      dex.config: |
        connectors:
          # Auth using GitHub.
          # See https://dexidp.io/docs/connectors/github/
          - type: github
            id: github
            name: GitHub
            config:
              clientID: 7f3abd487bd532d66a6c
              # Reference to key in argo-secret Kubernetes resource
              clientSecret: $dex.clientSecret
              orgs:
                - name: lsst-sqre
      helm.repositories: |
        - url: https://lsst-sqre.github.io/charts/
          name: lsst-sqre
        - url: https://ricoberger.github.io/helm-charts/
          name: ricoberger
        - url: https://kubernetes.github.io/ingress-nginx/
          name: ingress-nginx
        - url: https://charts.helm.sh/stable
          name: stable
        - url: https://strimzi.io/charts/
          name: strimzi
      resource.customizations.health.Job: |
        print ("LUA:JOB CHECK")
        hs = {}
        hs.status = "Progressing"
        if obj.metadata.labels.csc ~= nil then
          if obj.metadata.labels.csc == "dsm2-sim" then
            if obj.status ~= nil then
              if obj.status.conditions ~= nil then
                for i, condition in ipairs(obj.status.conditions) do
                  if condition.type == "Ready" and condition.status == "False" then
                    hs.status = "Degraded"
                    hs.message = condition.message
                    return hs
                  end
                  if condition.type == "Ready" and condition.status == "True" then
                    hs.status = "Healthy"
                    hs.message = condition.message
                    return hs
                  end
                end
              end
            end
          end
        end
        return hs
      resource.customizations.useOpenLibs.Job: "true"

    rbacConfig:
      policy.csv: |
        g, lsst-sqre:square, role:admin

  configs:
    secret:
      createSecret: false

vault_secret:
  enabled: true
  path: secret/k8s_operator/tucson-teststand.lsst.codes/argocd

pull-secret:
  enabled: true
  path: secret/k8s_operator/tucson-teststand.lsst.codes/pull-secret
