# Default values for squareone.

# -- Number of squareone pods to run in the deployment.
replicaCount: 1

image:
  # -- Squareone Docker image repository
  repository: ghcr.io/lsst-sqre/squareone

  # -- Image pull policy (tip: use Always for development)
  pullPolicy: IfNotPresent

  # -- Overrides the image tag.
  # @default -- Chart's appVersion
  tag: ""

# -- Overrides the base name for resources
nameOverride: ""

# -- Overrides the full name for resources (includes the release name)
fullnameOverride: ""

# -- Annotations for squareone pods
podAnnotations: {}

ingress:
  # -- Enable ingress
  enabled: true

  # -- Additional annotations to add to the ingress
  annotations: {}

  # -- Enable Let's Encrypt TLS management in this chart. This should be false
  # if TLS is managed elsewhere, such as in an ingress-nginx app.
  tls: true

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Squareone app configuration
config:
  # -- Name of the site, used in the title and meta tags.
  siteName: "Rubin Science Platform"

  # -- Site description, used in meta tags
  siteDescription: |
    Access Rubin Observatory Legacy Survey of Space and Time data.

  # -- URL to the Semaphore (user notifications) API service.
  # @default null disables the Semaphore integration
  semaphoreUrl: null

  # -- URL to the Times Square (parameterized notebooks) API service.
  # @default null disables the Times Square integration
  timesSquareUrl: null

  # -- URL to the COmanage registry, if the environment uses COmanage for identity.
  # @default null disables the COmanage integration
  coManageRegistryUrl: null

  # -- MDX content for the `/support` page
  supportPageMdx: |
    # Get help with the Rubin Science Platform

    <Lede>Besides the <Link href="/docs">documentation</Link>, you can get help
    from Rubin Observatory staff. Here are the ways to ask for help.</Lede>

    <Section>
      ## Data Preview 0 science questions

      For questions about the Data Preview dataset (DESC DC2) and analyzing
      that data (such as with the LSST Science Pipelines), create a new
      topic in the [Data Preview 0 Support category](https://community.lsst.org/c/support/dp0/49)
      of the Community forum.

      <CtaLink href="http://community.lsst.org/new-topic?category=support/dp0">Create a science support topic in the forum</CtaLink>
    </Section>

    <Section>
      ## Rubin Science Platform technical support and feature requests

      For technical issues or feature requests related to the Rubin Science
      Platform itself (the Portal, Notebooks, and API services such as TAP)
      create a GitHub issue in the
      [rubin-dp0/Support](https://github.com/rubin-dp0/Support) repository.

      <CtaLink href="https://github.com/rubin-dp0/Support/issues/new/choose">Create a GitHub issue</CtaLink>
    </Section>

  # -- MDX content for the `/enrollment/thanks-for-signing-up` page
  verifyEmailPageMdx: |
    # Thanks for registering

    <Lede>You'll receive an email from us shortly. Click on the link in the
    message to verify your address and continue your account set up.</Lede>

  # -- MDX content for the `/enrollment/thanks-for-verifying` page
  emailVerifiedPageMdx: |
    # Your email is verified

    <Lede>We are reviewing your application. You’ll receive an email as soon as
    your account is approved.</Lede>

  # -- MDX content for the `/enrollment/pending-approval` page
  pendingApprovalPageMdx: |
    # Your account is pending approval

    <Lede>Requests are typically processed within five business days.</Lede>

    Once your account is approved, you’ll receive an email at the address
    you registered with.

    <Link href="../support"><a>Contact us</a></Link> if you have further questions.

  # -- MDX content for the `/enrollment/pending-confirmation`
  pendingVerificationPageMdx: |
    # Please confirm your email

    <Lede>Your email is still pending verification.</Lede>

    To complete your enrollment please check the email you registered with
    for a link to verify your email address. Please click on the link to
    verify your email address.

    If you have not received the confirmation email please check your SPAM folder.

    If you still cannot find the confirmation email please
    <Link href="../support"><a>contact us</a></Link> to have the confirmation
    email resent.

# Global parameters are set by parameters injected by the Argo CD Application
# and should not be set in the individual environment values files.
global:
  # -- Base URL for the environment
  # @default -- Set by Argo CD Application
  baseUrl: ""

  # -- Host name for ingress
  # @default -- Set by Argo CD Application
  host: ""

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD Application
  vaultSecretsPathPrefix: ""
